name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black bandit

      - name: Lint with flake8
        run: flake8 .

      - name: Check formatting with black
        run: black --check .

      - name: Security analysis with bandit
        run: bandit -r . --exclude venv

      - name: Run tests
        run: pytest

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # change to true to push image to registry
          tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-ci-cd-demo:latest
