name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black bandit

      - name: Lint with flake8
        run: flake8 .

      - name: Check formatting with black
        run: black --check .

      - name: Security analysis with bandit
        run: bandit -r . --exclude venv

      - name: Run tests
        run: pytest

      - name: Determine Docker tag and push setting
        id: meta
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "tag=${{ secrets.DOCKER_USERNAME }}/fastapi-ci-cd-demo:latest" >>"$GITHUB_OUTPUT"
            echo "push=true" >>"$GITHUB_OUTPUT"
          else
            echo "tag=fastapi-ci-cd-demo:latest" >>"$GITHUB_OUTPUT"
            echo "push=false" >>"$GITHUB_OUTPUT"
          fi

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ steps.meta.outputs.push }}
          tags: ${{ steps.meta.outputs.tag }}
